name: Master Branch Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECTNAME }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - uses: actions/checkout@v2
      - name: Log into Docker
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $PROJECT_TAG:latest
      - name: Tag the Docker image
        run: docker tag $PROJECT_TAG:latest $PROJECT_TAG:${{ steps.date.outputs.date }}
      - name: Push the Docker image
        run: docker push -a $PROJECT_TAG
